name: Build Container CI

on:
  push:
    branches: [ "main" ]
    paths: 
      - pdf/**
      - docker-compose.yml


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: pdf/
      run: cd docker build . --file Dockerfile --tag my-image-name:$(date +%s)
